film_blog/urls.py
from django.contrib import admin 
from django.conf import settings
from django.urls import path, include 


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('movie/', include("movie.urls")),
    path('serie/', include("serie.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("search_media", views.search_media, name="search_media"),
    path("search/", views.search, name="search"),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    path("register/", views.register, name="user-register"),
    path('register/update/', views.user_update, name='user-update'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

movie/urls.py
from django.urls import path 
from movie import views 

app_name = "movie"
urlpatterns = [
    path("movies/", views.MovieListView.as_view(), name="movie-list"),
    path("movie/add/", views.MovieCreateView.as_view(), name="movie-add"),
    path("movie/<int:pk>/detail/", views.MovieDetailView.as_view(), name="movie-detail"),
    path("movie/<int:pk>/update/", views.MovieUpdateView.as_view(), name="movie-update"),
    path("movie/<int:pk>/delete/", views.MovieDeleteView.as_view(), name="movie-delete"),
    path("comment/<int:pk>/add/", views.CommentCreateView.as_view(), name="comment-create"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
]

serie/urls.py
from django.urls import path 
from serie import views 

app_name = "serie"
urlpatterns = [
    path("series/", views.SerieListView.as_view(), name="serie-list"),
    path("serie/add/", views.SerieCreateView.as_view(), name="serie-add"),
    path("serie/<int:pk>/detail/", views.SerieDetailView.as_view(), name="serie-detail"),
    path("serie/<int:pk>/update/", views.SerieUpdateView.as_view(), name="serie-update"),
    path("serie/<int:pk>/delete/", views.SerieDeleteView.as_view(), name="serie-delete"),
    path("comment/<int:pk>/add/", views.CommentCreateView.as_view(), name="comment-create"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
]

home/models.py
from django.contrib.auth.models import User
from django.db import models


class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='avatar', null=True, blank=True)

    def __str__(self):
        return f'user: {self.user.username} | url: {self.image.url}'

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from home.models import Avatar


class UserRegisterForm(UserCreationForm):

    username = forms.CharField(label="Usuario", min_length=3)
    first_name = forms.CharField(label="Nombre", min_length=3)
    last_name = forms.CharField(label="Apellido", min_length=3)
    email = forms.EmailField(label="Correo electrónico")
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirmar contraseña", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]


class UserUpdateForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = [
            "email",
            "first_name",
            "last_name",
        ]
        widgets = {
            "email": forms.TextInput(attrs={"readonly": "readonly"}),
        }

class AvatarForm(forms.ModelForm):
    image = forms.ImageField()
    class Meta:
        model = Avatar
        fields = ("image", )
        

home/views.py
from django.db.models import Q
from django.shortcuts import render
import os

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from django.shortcuts import redirect

from movie.models import Movie
from serie.models import Serie
from home.forms import UserRegisterForm
from home.forms import UserUpdateForm
from home.models import Avatar
from home.forms import AvatarForm

def get_avatar_url_ctx(request):
    avatars = Avatar.objects.filter(user=request.user.id)
    if avatars.exists():
        return {"avatar_url": avatars[0].image.url}
    return {}

def index(request):
    return render(
        request=request,
        context= get_avatar_url_ctx(request),
        template_name="home/index.html",
    )

def search_media(request):
    return render(
        request=request,
        template_name = "home/search.html"
    )

def search(request):
    search_param = request.GET["search_param"]
    print("search: ", search_param)
    context_dict = dict()
    
    if search_param:
        query = Q(title__contains=search_param)
        query.add(Q(genre__contains=search_param), Q.OR)
        movies = Movie.objects.filter(query)
        series = Serie.objects.filter(query)
        context_dict.update(
            {
                "movies": movies,
                "series": series,
                "search_param": search_param,
            }
        )
    return render(
        request=request,
        context=context_dict,
        template_name="home/search.html",
    )

def register(request):
    form = UserRegisterForm(request.POST) if request.POST else UserRegisterForm()
    if request.method == "POST":
        if form.is_valid(): 
            form.save()
            messages.success(request, "Usuario creado exitosamente!")
            return redirect("login")

    return render(
        request=request,
        context={"form": form},
        template_name="registration/register.html",
    )


@login_required
def user_update(request):
    user = request.user
    if request.method == "POST":
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("home:index")

    form = UserUpdateForm(model_to_dict(user))
    avatars = Avatar.objects.filter(user=request.user.id)

    if avatars.exists():
        dictionary = {"form": form, "avatar_url": avatars[0].image.url}
    else:
        dictionary = {"form": form}

    return render(
        request=request,
        context=dictionary,
        template_name="registration/user_form.html",
    )

@login_required
def avatar_load(request):
    if request.method == "POST":
        form = AvatarForm(request.POST, request.FILES)
        if form.is_valid and len(request.FILES) != 0:
            image = request.FILES["image"]
            avatars = Avatar.objects.filter(user=request.user.id)
            if not avatars.exists():
                avatar = Avatar(user=request.user, image=image)
            else:
                avatar = avatars[0]
                if len(avatar.image) > 0:
                    os.remove(avatar.image.path)
                avatar.image = image
            avatar.save()
            messages.success(request, "Imagen cargada exitosamente")
            return redirect("home:index")

    form = AvatarForm()
    return render(
        request=request,
        context={"form": form},
        template_name="home/avatar_form.html",
    )

home/templates/home/avatar_form.html
{% extends "home/index.html" %}
{% load static %}

{% block film_blog_title %}
Avatar Load
{% endblock %}

{% block film_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Cargar Imagen de Avatar</h1>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block film_blog_content %}
    <h1 style="text-align:center">Usuario: {{user.username}} | {{user.first_name}} {{user.last_name}}</h1>
    <form method="POST" enctype="multipart/form-data" style="text-align:center">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Cargar Imagen</button>
    </form>
{% endblock %}

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block film_blog_title %}
                Moviecon - Home
            {% endblock %}
        </title>
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home:index' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home:search_media' %}">Buscador</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'movie:movie-list' %}">Movies</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'serie:serie-list' %}">Series</a></li>
                        
                        <div class="topbar-divider d-none d-sm-block"></div>
                        
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home:user-update' %}">Editar usuario</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'logout' %}">Cerrar Sesión - {{ user.username }}</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'login' %}">Iniciar Sesión</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block film_blog_header %}

        <!-- Page Header-->
        <header class="masthead" style="background-image: url('../../static/home/assets/img/cine.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            {% if user.is_authenticated %}
                                <p style="text-align:left"><small>Registrado como:</small></p>
                                <h2>{{ user.first_name }} {{ user.last_name }} | {{ user.username}}</h2>
                                
                            {% else %}
                                <h1>Moviecon</h1>
                                <h2>Bienvenido - registrate e inicia sesion</h2>
                                <span class="subheading">Let's have fun</span>

                            {% endif %}
                            {% if avatar_url %}
                                <a><img height="260px" src="{{avatar_url}}"></a>
                            {% endif %}
                            <!-- <div style="background-color: #ffffff; width: 87%;" color>Avatar URL: {{ avatar_url }}</div> -->
                            {% if not avatar_url %}
                                <a class="button_custom" href="{% url 'home:avatar-load' %}">Cargar Avatar</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <!-- <div style="background-color: #ffffff; width: 87%;" color>Avatar URL: {{ avatar_url }}</div> -->
                {% if user.is_authenticated %}
                    {% if not avatar_url %}
                    <a class="button_custom" href="{% url 'home:avatar-load' %}">Cargar Avatar</a>
                    {% endif %}
                {% endif %}
            </div>

        </header>
        {% endblock %}

            <!-- Messages-->
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert {{ message.tags }}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                            <!-- Divider-->
                            <hr class="my-4" />
                        {% endif %}
                    </div>
                </div>
            </div>

        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    
                    {% block film_blog_content %}

                    <!-- Post preview-->
                    <div class="#!">
                        <a href="#!">

                        </a>
                        <div style="text-align:center">
                            <h1>Acerca de la pagina web</h1><hr>
                            <p>Esta una pagina web en la cual puedes encontrar apartados de las mejores peliculas y series conocidas. Estos apartados estan diseñados para darte una breve synopsis de cada una de peliculas o series para que así puedas compartir y comentar tu opinión/review.</p>
                            <p>Para esto deberas registrarte, loguearte, ir la buscador y buscar la pelicula o serie, y en la parte inferior de los detalles de las peliculas, podreas realizar tu comentario/review.</p><hr>


                            <h1>Acerca de los autores</h1><hr>
                                <h6 class="post-title"> Somos los mejores en python</h6>
                                <h6 class="post-subtitle"> Bueno quizas no los mejores pero nos esforzamos mucho</h6>
                            <hr><h3>Silvina Rodriguez</h3>
                            <p>Soy Silvina Rodriguez, me gusta tomar cursos de programación.</p>
                            <hr><h3>Juan Pablo Gómez Cristancho</h3>
                            <p>Soy Juan Pablo Gómez Cristancho, me gusta tomar cursos de programación.</p>
                            <hr><h3>Jose Fernandez</h3>
                            <p>Soy Jose Fernandez, me gusta tomar cursos de programación.</p>
                        </div>
                    </div>
                    <!-- Pager-->
                    {% endblock %}
                    {% block pagination %}
                        <!--Pagination Class Based Views-->
                        {% if is_paginated %}
                        <div class="container p-4">
                            <div class="pagination justify-content-center">
                                <span class="step-links">
                                    {% if page_obj.has_previous %}
                                        <a href="?page=1">&laquo; first</a> |
                                        <a href="?page={{ course_list.previous_page_number }}">previous</a> |
                                    {% endif %}
                        
                                    {% if page_obj.paginator.num_pages > 1 %}
                                    <span class="current">
                                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} |
                                    </span>
                                    {% endif %}
                        
                                    {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}">next</a> |
                                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                                    {% endif %}
                                </span>
                            </div>
                        </div>
                        {% endif %}
                        <!--end of Pagination-->
                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
    </body>
</html>

home/templates/home/search.html
{% extends "home/index.html" %}
{% load static %}

{% block film_blog_header %}
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('../../static/home/assets/img/Series.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                            <h1>Buscador de contenido</h1>
                    </div>
                </div>
            </div>
            <!-- <div style="background-color: #ffffff; width: 87%;" color>Avatar URL: {{ avatar_url }}</div> -->
        </div>
    </header>
{% endblock %}


{% block film_blog_content %}
        <!-- Buscador -->
        <div class="post-preview" style="text-align:center">
            <h1 >Busca una pelicula o una serie:</h1>
            <p class="post-meta" >
                Ya sea por un nombre o por un genero.
            </p>
        </div>
        
    
        <form action="{% url 'home:search' %}" method="GET">
            <div style="text-align:center">
                <input type="text" name="search_param" id="movie_title" placeholder="Buscar..."
                {% if search_param %} value="{{ search_param }}" {% endif %}
                >
                <input type="submit" value="Buscar">
                <a style="color: blue" href="{% url 'home:search_media' %}"><i class="fa fa-undo"></i></a>
            </div>
        </form>
        <!-- Divider-->
        <hr class="my-4" />

        <!-- Si hay resultados en el buscador los presenta -->
        {% if movies %}
            {% for movie in movies %}
                <div class="post-preview" >
                    <a href="{% url 'movie:movie-detail' movie.id %}">
                        <h2 class="post-title">Pelicula: {{ movie.title }}</h2>
                        <h3 class="post-subtitle">Genero: {{ movie.genre }}</h3>
                    </a>
                    <p class="post-meta">
                        Creado por
                        <a>{{ movie.owner.username }}</a> 
                        en {{ movie.created_at }}
                    </p>
                </div>
                <hr class="my-4" />
            {% endfor %}
        {% endif %}
        {% if series %}
            {% for serie in series %}
                <div class="post-preview" >
                    <a href="{% url 'serie:serie-detail' serie.id %}">
                        <h2 class="post-title">Serie: {{ serie.title }}</h2>
                        <h3 class="post-subtitle">Genero: {{ serie.genre }}</h3>
                    </a>
                    <p class="post-meta">
                        Creado por
                        <a>{{ serie.owner.username }}</a> 
                        en {{ serie.created_at }}
                    </p>
                </div>
                <hr class="my-4" />
            {% endfor %}
        
        {% endif %}
        
        {% if not movies and not series %}
            <p class="post-meta" style="text-align:center">
                Por el momento no se encontro ninguna referencia.
            </p>
        {% endif %}

{% endblock %}