film_blog/urls.py
from django.contrib import admin 
from django.conf import settings
from django.urls import path, include 


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('movie/', include("movie.urls")),
    path('serie/', include("serie.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("search_media", views.search_media, name="search_media"),
    path("search/", views.search, name="search"),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    path("register/", views.register, name="user-register"),
    path('register/update/', views.user_update, name='user-update'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

serie/urls.py
from django.urls import path 
from serie import views 

app_name = "serie"
urlpatterns = [
    path("series/", views.SerieListView.as_view(), name="serie-list"),
    path("serie/add/", views.SerieCreateView.as_view(), name="serie-add"),
    path("serie/<int:pk>/detail/", views.SerieDetailView.as_view(), name="serie-detail"),
    path("serie/<int:pk>/update/", views.SerieUpdateView.as_view(), name="serie-update"),
    path("serie/<int:pk>/delete/", views.SerieDeleteView.as_view(), name="serie-delete"),
    path("comment/<int:pk>/add/", views.CommentCreateView.as_view(), name="comment-create"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
]

serie/models.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models
from ckeditor.fields import RichTextField

class Serie(models.Model):
    title = models.CharField(max_length=40, null=False, blank=False)
    genre =  models.CharField(max_length=40, null=False, blank=False)
    chapters_number = models.IntegerField(null=False, blank=False)
    seasons_number = models.IntegerField(null=False, blank=False)
    duration =  models.IntegerField(null=False, blank=False)
    description =  RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to='serie', null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    comments = models.ManyToManyField(
        User, through="Comment_serie", related_name="comments_owned_serie"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 

    class Meta:
        unique_together = (
            "title",
            "genre",
            "chapters_number",
            "seasons_number",
            "duration",
            "description",
        )
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.title} - {self.genre} - {self.duration} - {self.description}"


class Comment_serie(models.Model):
    text = models.TextField(
        validators=[
            MinLengthValidator(10, "El comentario debe ser mayor de 10 caracteres")
        ]
    )
    serie = models.ForeignKey(Serie, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

serie/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from serie.models import Serie

class SerieForm(forms.ModelForm):
    title = forms.CharField(
        label="Nombre de la serie",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "serie-title",
                "placeholder": "Nombre de la serie",
                "required": "True",
            }
        ),
    )


    genre = forms.CharField(
        label="Genero",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "serie-title",
                "placeholder": "Genero de la serie",
                "required": "True",
            }
        ),
    )

    seasons_number = forms.IntegerField(
        label="Temporadas",
        required=False,
        widget=forms.NumberInput(
            attrs={
                "class": "serie-title",
                "placeholder": "Numero",
                "required": "True",
            }
        ),
    )

    chapters_number = forms.IntegerField(
        label="Capitulos",
        required=False,
        widget=forms.NumberInput(
            attrs={
                "class": "serie-title",
                "placeholder": "Numero",
                "required": "True",
            }
        ),
    )

    duration = forms.IntegerField(
        label="Duracion",
        required=False,
        widget=forms.NumberInput(
            attrs={
                "class": "serie-title",
                "placeholder": "Minutos por capitulo",
                "required": "True",
            }
        ),
    )


    description = forms.CharField(
        label="Descripcion:",
        required=False,
        widget=CKEditorWidget(
            attrs={
                "class": "serie-description",
                "placeholder": "Descripcion de la serie",
                "required": "True",
            }
        ),
    )
 
    image = forms.ImageField()

    class Meta:
        model = Serie
        fields = ["title", "genre","seasons_number", "chapters_number", "duration", "description", "image"]


class CommentForm(forms.Form):
        comment_text = forms.CharField(
        label="",
        required=False,
        max_length=500,
        min_length=10,
        strip=True,
        widget=forms.Textarea(
            attrs={
                "class": "comment-text",
                "placeholder": "Ingrese su comentario...",
                "required": "True",
                "max_length": 500,
                "min_length": 10,
                "rows": 2,
                "cols": 10,
                "style":"min-width: 100%",
            }
        ),
    )    

serie/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from serie.forms import CommentForm
from serie.forms import SerieForm
from serie.models import Comment_serie
from serie.models import Serie

class SerieListView(ListView):
    model = Serie
    paginate_by = 3
    #template_name = "movie/movie_list.html" --> No es necesario ya que Django busca automatico el html con el nombre_list.

class SerieDetailView(DetailView):
    model = Serie
    template_name = "serie/serie_detail.html"
    fields = ["title", "genre", "duration", "description"]

    def get(self, request, pk):
        serie = Serie.objects.get(id=pk)
        comments = Comment_serie.objects.filter(serie=serie).order_by("-updated_at")
        comment_form = CommentForm()
        context = {
            "serie": serie,
            "comments": comments,
            "comment_form": comment_form,
        }
        return render(request, self.template_name, context)


class SerieCreateView(LoginRequiredMixin, CreateView):
    model = Serie
    success_url = reverse_lazy("serie:serie-list")

    form_class = SerieForm
    # fields = ["title", "genre", "duration", "description"]

    def form_valid(self, form):
        """Filter to avoid duplicate series"""
        data = form.cleaned_data
        form.instance.owner = self.request.user
        actual_objects = Serie.objects.filter(
            title=data["title"], genre=data["genre"]
        ).count()
        if actual_objects:
            messages.error(
                self.request,
                f"La serie {data['title']} - {data['genre']} ya está creada",
            )
            form.add_error("title", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"Serie {data['title']} - {data['genre']} creada exitosamente!",
            )
            return super().form_valid(form)

class SerieUpdateView(LoginRequiredMixin, UpdateView):
    model = Serie
    fields = ["title", "genre", "duration", "description", "image"]

    def get_success_url(self):
        serie_id = self.kwargs["pk"]
        return reverse_lazy("serie:serie-detail", kwargs={"pk": serie_id})

class SerieDeleteView(LoginRequiredMixin, DeleteView):
    model = Serie
    success_url = reverse_lazy("serie:serie-list")

class CommentCreateView(LoginRequiredMixin, CreateView):
    def post(self, request, pk):
        serie = get_object_or_404(Serie, id=pk)
        comment = Comment_serie(
            text=request.POST["comment_text"], owner=request.user, serie=serie
        )
        comment.save()
        return redirect(reverse("serie:serie-detail", kwargs={"pk": pk}))


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment_serie

    def get_success_url(self):
        serie = self.object.serie
        return reverse("serie:serie-detail", kwargs={"pk": serie.id})

serie/templates/serie/comment_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block film_blog_title %}
Comentario delete
{% endblock %}

{% block film_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Eliminar Comentario</h1>
                    <span class="subheading">Creado por: {{ comment.owner.first_name }} {{ comment.owner.last_name }}</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block film_blog_content %}

<h1>Estás seguro de eliminar el siguiente Comentario?</h1>
<p>{{ comment.text }}</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'serie:serie-detail' comment.serie.id %}" >Cancelar</a>
</form>

{% endblock %}

serie/templates/serie/serie_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block film_blog_title %}
Serie delete
{% endblock %}

{% block film_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ serie.name }}</h1>
                    <h1>Eliminar serie</h1>
                </div>
            </div>
        </div>
</header>
{% endblock %}


{% block film_blog_content %}

<h1 style="text-align:center">Estás seguro de eliminar la serie: {{ serie.title }}?</h1>

<form style="text-align:center" action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'serie:serie-list' %}" >Cancelar</a>
</form>

{% endblock %}

serie/templates/serie/serie_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block film_blog_title %}
Serie detail
{% endblock %}

{% block film_blog_header %}
    {% if not serie.image %}
    <header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    {% else %}
    <header class="masthead" style="background-image:url('{{ serie.image.url }}')">
    {% endif %}
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>{{ serie.title }}</h1>
                        <span class="subheading">Detalles de la serie</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}


{% block film_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <h2 class="post-subtitle" style="text-align:center"> Titulo oficial: {{serie.title}}</h2>
    <hr>
    <p class="post-meta">
        Genero: {{ serie.genre }} <br>
        Temporadas: {{ serie.seasons_number}} <br>
        Numero de capitulos: {{ serie.chapters_number}} <br>
        Duración de capitulos: {{ serie.duration}} <br>
    </p>
    <hr>
    <!-- Image -->
    {% if serie.image %}
        <div style="text-align: center;">
            <img height="250px" src="{{ serie.image.url }}">
        </div>
    {% endif %}
    <hr>

    <p class="post-meta">
        Apartado creado por 
        <span style="color: #0b4956;" href="">{{ serie.owner.username }}</span>
        ( {{ serie.created_at }} )
        <br>
        Última fecha de actualización {{ serie.updated_at }}
    </p>

    <!-- Description -->
    <h3>Sinopsis: </h3>
    <p class="card-text ">{{ serie.description|safe }}</p> <!-- ckeditor-->
    
    <!-- Update-Delete link only for the owner -->
    {% if user.is_superuser %}
    <p style="text-align: center">
        <a href="{% url 'serie:serie-update' serie.id %}">
            <i class="fa fa-pencil" style="color: #1c1c91;"></i> Editar serie
        </a>
        &ensp; | &ensp;
        <a href="{% url 'serie:serie-delete' serie.id %}">
            <i class="fa fa-trash" style="color: #881a1a;"></i> Eliminar serie
        </a>
    </p>
{% endif %}

<!-- Divider-->
<hr class="my-4" />

<!-- Comment creation -->
<form method="post" action="{% url 'serie:comment-create' serie.id %}">
    {% csrf_token %}
    {{ comment_form }}
<input type="submit" value="Publicar comentario">
</form>
{% if not comments %}
    <p></p>
{% endif %}

<!-- Comments list -->
{% for comment in comments %}
    <p> {{ comment.text }}
        ({{ comment.owner.username }} | {{ comment.updated_at }})
        {% if user == comment.owner or user.is_superuser %}
        <a href="{% url 'serie:comment-delete' comment.id %}"><i class="fa fa-trash" style="color: #881a1a;"></i></a>
        {% endif %}
    </p>
{% endfor %}
</div>
{% endblock %}

serie/templates/serie/serie_form.html
{% extends "home/index.html" %}
{% load static %}

<!-- ckeditor-->
{% block extrahead %}
    <script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}
<!-- ckeditor-->

{% block film_blog_title %}
    Serie Create-Update
{% endblock %}

{% block film_blog_header %}
    {% if not serie.image %}
    <header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    {% else %}
    <header class="masthead" style="background-image:url('{{ serie.image.url }}')">
    {% endif %}
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Formulario para guardar/editar series</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block film_blog_content %}
    {% if user.is_staff %}
        <div style="text-align:center">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }} <!-- ckeditor-->
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary" value="Guardar serie" />
            </form>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endif %}
{% endblock %}

serie/templates/serie/serie_list.html
{% extends "home/index.html" %}

{% load static %}

{% block film_blog_title %}
Serie list
{% endblock %}

{% block film_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/peliculas.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Listado de series</h1>
                </div>
            </div>
        </div>
        {% if user.is_authenticated and user.is_staff %}
        <a class="button_custom" href="{% url 'serie:serie-add' %}">Crear nueva Serie</a>
        {% endif %}
    </div>
</header>
{% endblock %}

{% block film_blog_content %}
    {% for serie in serie_list %}
        <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'serie:serie-detail' serie.id %}">
                <h2 class="post-title">Titulo: {{ serie.title }}</h2>
                <h3 class="post-subtitle">Genero: {{ serie.genre}}</h3>
                <h3 class="post-subtitle">Temporadas: {{ serie.seasons_number}}</h3>
                <h3 class="post-subtitle">Capitulos: {{ serie.chapters_number}} x {{ serie.duration}} minutos</h3>
            </a>
            <p class="post-meta">
                Creado por
                <span style="color: #0b4956;" href="">{{ serie.owner.username }}</span>
                ( {{ serie.created_at }} )
            </p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}