film_blog/urls.py
from django.contrib import admin 
from django.conf import settings
from django.urls import path, include 


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('movie/', include("movie.urls")),
    path('serie/', include("serie.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("search_media", views.search_media, name="search_media"),
    path("search/", views.search, name="search"),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    path("register/", views.register, name="user-register"),
    path('register/update/', views.user_update, name='user-update'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

movie/urls.py
from django.urls import path 
from movie import views 

app_name = "movie"
urlpatterns = [
    path("movies/", views.MovieListView.as_view(), name="movie-list"),
    path("movie/add/", views.MovieCreateView.as_view(), name="movie-add"),
    path("movie/<int:pk>/detail/", views.MovieDetailView.as_view(), name="movie-detail"),
    path("movie/<int:pk>/update/", views.MovieUpdateView.as_view(), name="movie-update"),
    path("movie/<int:pk>/delete/", views.MovieDeleteView.as_view(), name="movie-delete"),
    path("comment/<int:pk>/add/", views.CommentCreateView.as_view(), name="comment-create"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
]

movie/models.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models
from ckeditor.fields import RichTextField

class Movie(models.Model):
    title = models.CharField(max_length=40, null=False, blank=False)
    genre =  models.CharField(max_length=40, null=False, blank=False)
    duration =  models.IntegerField(null=False, blank=False)
    description =  RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to='movie', null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    comments = models.ManyToManyField(
        User, through="Comment", related_name="comments_owned"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 

    class Meta:
        unique_together = (
            "title",
            "genre",
            "duration",
            "description",
        )
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.title} - {self.genre} - {self.duration} - {self.description}"


class Comment(models.Model):
    text = models.TextField(
        validators=[
            MinLengthValidator(10, "El comentario debe ser mayor de 10 caracteres")
        ]
    )
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

movie/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from movie.models import Movie


class MovieForm(forms.ModelForm):
    title = forms.CharField(
        label="Nombre de la pelicula",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "movie-title",
                "placeholder": "Nombre de la pelicula",
                "required": "True",
            }
        ),
    )


    genre = forms.CharField(
        label="Genero",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "movie-title",
                "placeholder": "Genero de la pelicula",
                "required": "True",
            }
        ),
    )
    duration = forms.IntegerField(
        label="Duracion",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "movie-title",
                "placeholder": "Duracion de la pelicula",
                "required": "True",
            }
        ),
    )

    description = forms.CharField(
        label="Descripcion:",
        required=False,
        widget=CKEditorWidget(
            attrs={
                "class": "movie-description",
                "placeholder": "Descripcion de la pelicula",
                "required": "True",
            }
        ),
    )
 
    image = forms.ImageField()

    class Meta:
        model = Movie
        fields = ["title", "genre", "duration", "description", "image"]


class CommentForm(forms.Form):
        comment_text = forms.CharField(
        label="",
        required=False,
        max_length=500,
        min_length=10,
        strip=True,
        widget=forms.Textarea(
            attrs={
                "class": "comment-text",
                "placeholder": "Ingrese su comentario...",
                "required": "True",
                "max_length": 500,
                "min_length": 10,
                "rows": 2,
                "cols": 10,
                "style":"min-width: 100%",
            }
        ),
    )    

movie/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from movie.forms import CommentForm
from movie.forms import MovieForm
from movie.models import Comment
from movie.models import Movie



class MovieListView(ListView):
    model = Movie
    paginate_by = 3
    #template_name = "movie/movie_list.html" --> No es necesario ya que Django busca automatico el html con el nombre_list.


class MovieDetailView(DetailView):
    model = Movie
    template_name = "movie/movie_detail.html"
    fields = ["title", "genre", "duration", "description"]

    def get(self, request, pk):
        movie = Movie.objects.get(id=pk)
        comments = Comment.objects.filter(movie=movie).order_by("-updated_at")
        comment_form = CommentForm()
        context = {
            "movie": movie,
            "comments": comments,
            "comment_form": comment_form,
        }
        return render(request, self.template_name, context)


class MovieCreateView(LoginRequiredMixin, CreateView):
    model = Movie
    success_url = reverse_lazy("movie:movie-list")

    form_class = MovieForm
    # fields = ["title", "genre", "duration", "description", "image"]

    def form_valid(self, form):
        """Filter to avoid duplicate movies"""
        data = form.cleaned_data
        form.instance.owner = self.request.user
        actual_objects = Movie.objects.filter(
            title=data["title"], genre=data["genre"]
        ).count()
        if actual_objects:
            messages.error(
                self.request,
                f"La pelicula {data['title']} - {data['genre']} ya está creado",
            )
            form.add_error("title", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"Pelicula {data['title']} - {data['genre']} creado exitosamente!",
            )
            return super().form_valid(form)


class MovieUpdateView(LoginRequiredMixin, UpdateView):
    model = Movie
    fields = ["title", "genre", "duration", "description", "image"]

    def get_success_url(self):
        movie_id = self.kwargs["pk"]
        return reverse_lazy("movie:movie-detail", kwargs={"pk": movie_id})
    
    def post(self):
        pass

class MovieDeleteView(LoginRequiredMixin, DeleteView):
    model = Movie
    success_url = reverse_lazy("movie:movie-list")


class CommentCreateView(LoginRequiredMixin, CreateView):
    def post(self, request, pk):
        movie = get_object_or_404(Movie, id=pk)
        comment = Comment(
            text=request.POST["comment_text"], owner=request.user, movie=movie
        )
        comment.save()
        return redirect(reverse("movie:movie-detail", kwargs={"pk": pk}))


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment

    def get_success_url(self):
        movie = self.object.movie
        return reverse("movie:movie-detail", kwargs={"pk": movie.id})

movie/templates/movie/comment_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block film_blog_title %}
Comentario delete
{% endblock %}

{% block film_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Eliminar Comentario</h1>
                    <span class="subheading">Creado por: {{ comment.owner.first_name }} {{ comment.owner.last_name }}</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block film_blog_content %}

<h1>Estás seguro de eliminar el siguiente Comentario?</h1>
<p>{{ comment.text }}</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'movie:movie-detail' comment.movie.id %}" >Cancelar</a>
</form>

{% endblock %}

movie/templates/movie/movie_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block film_blog_title %}
Movie delete
{% endblock %}

{% block film_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ movie.name }}</h1>
                    <h1>Eliminar pelicula</h1>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block film_blog_content %}

<h1 style="text-align:center">Estás seguro de eliminar la pelicula: {{ movie.title }}?</h1>

<form style="text-align:center" action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'movie:movie-list' %}" >Cancelar</a>
</form>

{% endblock %}

movie/templates/movie/movie_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block film_blog_title %}
Movie detail
{% endblock %}

{% block film_blog_header %}
    {% if not movie.image %}
    <header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    {% else %}
    <header class="masthead" style="background-image:url('{{ movie.image.url }}')">
    {% endif %}
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ movie.title }}</h1>
                    <span class="subheading">Detalles de la pelicula</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block film_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <h2 class="post-subtitle" style="text-align:center"> Titulo oficial: {{movie.title}}</h2>
    <hr>
    <p class="post-meta">
        Genero: {{ movie.genre }} <br>
        Duración: {{ movie.duration}} minutos<br>
    </p>
    <hr>
     <!-- Image -->
     {% if movie.image %}
        <div style="text-align: center;">
            <img height="250px" src="{{ movie.image.url }}">
        </div>
    {% endif %}
    <hr>

    <p class="post-meta">
        Apartado creado por 
        <span style="color: #0b4956;" href="">{{ movie.owner.username }}</span>
        ( {{ moviie.created_at }} )
        <br>
        Última fecha de actualización {{ movie.updated_at }}
    </p>

    <!-- Description -->
    <h3>Sinopsis: </h3>
    <p class="card-text ">{{ movie.description|safe }}</p> <!-- ckeditor-->
    
    <!-- Update-Delete link only for the owner -->
    {% if user.is_superuser %}
    <p style="text-align: center">
        <a href="{% url 'movie:movie-update' movie.id %}">
            <i class="fa fa-pencil" style="color: #1c1c91;"></i> Editar Pelicula
        </a>
        &ensp; | &ensp;
        <a href="{% url 'movie:movie-delete' movie.id %}">
            <i class="fa fa-trash" style="color: #881a1a;"></i> Eliminar Pelicula
        </a>
    </p>
{% endif %}

<!-- Divider-->
<hr class="my-4" />

<!-- Comment creation -->
<form method="post" action="{% url 'movie:comment-create' movie.id %}">
    {% csrf_token %}
    {{ comment_form }}
<input type="submit" value="Publicar comentario">
</form>
{% if not comments %}
    <p></p>
{% endif %}

<!-- Comments list -->
{% for comment in comments %}
    <p> {{ comment.text }}
        ({{ comment.owner.username }} | {{ comment.updated_at }})
        {% if user == comment.owner or user.is_superuser %}
        <a href="{% url 'movie:comment-delete' comment.id %}"><i class="fa fa-trash" style="color: #881a1a;"></i></a>
        {% endif %}
    </p>
{% endfor %}
</div>
{% endblock %}

movie/templates/movie/movie_form.html
{% extends "home/index.html" %}
{% load static %}

<!-- ckeditor-->
{% block extrahead %}
    <script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}
<!-- ckeditor-->

{% block film_blog_title %}
    Movie Create-Update
{% endblock %}

{% block film_blog_header %}
    {% if not movie.image %}
    <header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    {% else %}
    <header class="masthead" style="background-image:url('{{ movie.image.url }}')">
    {% endif %}
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Formulario para guardar/editar peliculas</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block film_blog_content %}
    {% if user.is_staff %}
        <div style="text-align:center">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }} <!-- ckeditor-->
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary" value="Guardar pelicula" />
            </form>
        </div>
    {% endif %}
    
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

movie/templates/movie/movie_list.html
{% extends "home/index.html" %}

{% load static %}

{% block film_blog_title %}
Movie list
{% endblock %}

{% block film_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/peliculas.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Listado de peliculas</h1>
                </div>
            </div>
        </div>
        {% if user.is_authenticated and user.is_staff %}
            <a class="button_custom" href="{% url 'movie:movie-add' %}">Crear nueva Pelicula</a>
        {% endif %}
    </div>
</header>
{% endblock %}


{% block film_blog_content %}
    {% for movie in movie_list %}
        <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'movie:movie-detail' movie.id %}">
                <h2 class="post-title">Titulo: {{ movie.title }}</h2>
                <h3 class="post-subtitle">Genero: {{ movie.genre}}</h3>
                <h3 class="post-subtitle">Duracion: {{ movie.duration}} minutos</h3>
            </a>
            <p class="post-meta">
                Creado por
                <span style="color: #0b4956;" href="">{{ movie.owner.username }}</span>
                ( {{ movie.created_at }} )
            </p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}